#!/bin/bash

if [ $# -eq 1 ]; then
    cd ~/workbench/$(ls ~/workbench/ | fzf)
else
    cd $2
fi

tmux new-session -s $1 \; rename-window 'Editor' \; send-keys 'nvim' C-m \; new-window \; rename-window 'Terminal' \; next-window \;
