#!/bin/zsh

if [ $# -eq 1 ]; then
    cd ~/workbench/projects/$(ls ~/workbench/projects/ | fzf)/www
else
    cd $2
fi

tmux new-session -s $1 \; rename-window 'Editor' \; send-keys 'nvim' C-m \; new-window \; rename-window 'Terminal' \; next-window \;
