#!/bin/bash

folder=~/Pictures/frame
xoffset=$(xrandr | grep 'HDMI-1' | sed -n 's/.*\([0-9]\{4\}x[0-9]\{4\}+\([0-9]\+\)+[0-9]\+\).*/\2/p')
yoffset=100

show-picture () {
    feh -x -g 0x0+0+0 $1
}
show-random-picture () {
    show-picture $(find $folder -maxdepth 1 -type f | shuf -n1)
}

show-random-picture
while sleep 300; do
    show-random-picture
done
